version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Install dependencies"
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Nothing to do in pre_build phase"

  build:
    commands:
      - echo "Nothing to do in build phase"

  post_build:
    commands:
      - echo "Build Docker image"
      - docker build -t myflaskapp .

artifacts:
  files:
    - app.py
    - tasks.json
    - requirements.txt
    - Dockerfile
